# Generated by Django 5.2.1 on 2025-06-05 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_cart_cartitem_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.size')),
            ],
        ),
    ]
