# Generated by Django 5.2.1 on 2025-06-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_productvariation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='size',
        ),
    ]
