# Generated by Django 5.2.1 on 2025-06-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_remove_productvariation_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='size',
            field=models.ManyToManyField(to='general.size'),
        ),
    ]
