# Generated by Django 5.2.1 on 2025-06-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_productvariation_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
